# --- Site settings ---
title: "Samson Orodele"
subtitle: "Data Analyst | Power BI | SQL | Excel | Python"
description: "Turning data into insights to drive smart business decisions"
author: "Samson Orodele"
email: your.email@example.com
url: "https://samsonorodele.github.io"
baseurl: ""  # Leave blank for GitHub Pages
repository: "SamsonOrodele/SamsonOrodele.github.io"
lang: "en"

# --- Social links ---
social-network-links:
  github: SamsonOrodele
  linkedin: your-linkedin-url  # <-- Replace with actual LinkedIn
  email: your.email@example.com
  rss: true

# --- Personalization ---
avatar: "/assets/profile.jpg"  # Optional: upload your profile pic to that path
favicon: "/favicon.ico"            # Optional: set if you have a favicon
keywords: "Data Analyst, Power BI, Excel, SQL, Python, Portfolio"
footer-text: "© 2025 Samson Orodele"

# --- Google Analytics (optional) ---
# google_analytics: G-XXXXXXXXXX

# --- Build settings ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: Europe/London

# --- Theme settings ---
remote_theme: daattali/beautiful-jekyll

# --- Navigation bar links ---
navbar-links:
  About Me: "aboutme"
  Projects:
    - "Oracle SQL Project": "https://github.com/SamsonOrodele/transportation-management"
    - "Power BI Analysis": "https://github.com/SamsonOrodele/Vrinda-Store-Data-Analysis"
    - "10Alytics Reporting": "https://github.com/SamsonOrodele"
  Resume: "assets/resume.pdf"  # Upload your resume here
  Contact: "contact"

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# --- Exclude from processing ---
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
