# --- Site settings ---
title: "Samson Orodele"
subtitle: "Data Analyst | Power BI | SQL | Excel | Python"
description: "Turning data into insights to drive smart business decisions"
author: "Samson Orodele"
email: "your.email@example.com"  # Replace with your real email
url: "https://samsonorodele.github.io"
baseurl: ""
repository: "SamsonOrodele/SamsonOrodele.github.io"
lang: "en"

# --- Social links ---
social-network-links:
  github: "SamsonOrodele"
  linkedin: "https://www.linkedin.com/in/your-profile"  # Replace with actual URL
  email: "your.email@example.com"
  rss: true

# --- Personalization ---
avatar: "https://raw.githubusercontent.com/SamsonOrodele/samsonorodele.github.io/main/assets/profile.jpg"
favicon: "/favicon.ico"
keywords: "Data Analyst, Power BI, Excel, SQL, Python, Portfolio"
footer-text: "© 2025 Samson Orodele"

# --- Build settings ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: Europe/London

# --- Theme settings ---
remote_theme: daattali/beautiful-jekyll

# --- Navigation bar links ---
navbar-links:
  About Me: "aboutme"
  Projects:
    - "Oracle SQL Project": "https://github.com/SamsonOrodele/transportation-management"
    - "Power BI Analysis": "https://github.com/SamsonOrodele/Vrinda-Store-Data-Analysis"
    - "10Alytics Reporting": "https://github.com/SamsonOrodele/10alytics-reporting"  # Assuming a specific repo; adjust if needed
    - "Project 4": "https://github.com/SamsonOrodele/project-4"  # Placeholder; replace with real repo
    - "Project 5": "https://github.com/SamsonOrodele/project-5"  # Placeholder
    - "Project 6": "https://github.com/SamsonOrodele/project-6"  # Placeholder
    - "Project 7": "https://github.com/SamsonOrodele/project-7"  # Placeholder
    - "Project 8": "https://github.com/SamsonOrodele/project-8"  # Placeholder
    - "Project 9": "https://github.com/SamsonOrodele/project-9"  # Placeholder
  Resume: "assets/resume.pdf"
  Contact: "contact"

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# --- Exclude from processing ---
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
