# --- Site settings ---
title: "Samson Orodele"
subtitle: "Data Analyst | Transforming Insights into Impact"
description: "Portfolio of Samson Orodele, a Data Analyst specializing in Power BI, SQL, Excel, and Python."
author: "Samson Orodele"
email: "your.email@example.com"  # Replace with your real email
url: "https://samsonorodele.github.io"
baseurl: ""
repository: "SamsonOrodele/SamsonOrodele.github.io"
lang: "en"

# --- Social links ---
social-network-links:
  github: "SamsonOrodele"
  linkedin: "https://www.linkedin.com/in/your-profile"  # Replace with your LinkedIn URL
  email: "your.email@example.com"
  rss: false

# --- Personalization ---
avatar: "/assets/profile.jpg"  # Relative path to avoid conflicts
favicon: "/assets/favicon.ico"  # Add if you have one
keywords: "Data Analyst, Power BI, SQL, Excel, Python, Data Visualization"
footer-text: "© 2025 Samson Orodele | Crafted with Precision"

# --- Theme settings ---
remote_theme: "daattali/beautiful-jekyll"
theme_color: "#1a2529"  # Navy background
navbar-col: "#1a2529"   # Navy navbar
navbar-text-col: "#f5f5f5"  # Soft white text
navbar-border-col: "#d4af37"  # Gold border
page-col: "#ffffff"  # White content background
text-col: "#2c3e50"  # Dark gray text
link-col: "#d4af37"  # Gold links
hover-col: "#b8860b"  # Darker gold on hover

# --- Custom CSS ---
beautifuljekyll_custom_css: |
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Roboto:wght@300;400&display=swap');
  body {
    font-family: 'Roboto', sans-serif;
    background-color: #f8f9fa;
  }
  h1, h2, h3 {
    font-family: 'Playfair Display', serif;
    color: #1a2529;
  }
  .navbar-custom {
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }
  .post-title, .post-subtitle {
    color: #1a2529;
  }
  .project-card {
    background: #ffffff;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }
  .project-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
  }
  .project-card a {
    color: #d4af37;
    text-decoration: none;
  }
  .project-card a:hover {
    color: #b8860b;
    text-decoration: underline;
  }
  #back-to-top {
    display: none !important;
  }
  .navbar-toggle {
    display: none !important; /* Hide mobile menu toggle */
  }
  .navbar-custom .navbar-nav {
    display: flex !important;
    flex-direction: row !important;
  }
  @media (max-width: 767px) {
    .navbar-custom .navbar-nav {
      flex-direction: row !important;
      flex-wrap: wrap !important;
    }
  }

# --- Build settings ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: Europe/London

# --- Navigation bar links ---
navbar-links:
  About: "about"
  Projects:
    - Transport Management System: "https://github.com/SamsonOrodele/Travel_Company_Database"
    - Breast Cancer Classification: "https://github.com/SamsonOrodele/Breast_Cancer_Classification"
    - M1 Motorway Traffic Analysis: "https://github.com/SamsonOrodele/M1-Motorway-Traffic-Analysis"
    - German Credit Risk Analysis: "https://github.com/SamsonOrodele/Explainable_AI"
    - Data Professionals Survey Dashboard: "https://github.com/SamsonOrodele/Data_Professional_Survey_PowerBI"
    - Excel Data Analysis Projects: "https://github.com/SamsonOrodele/Excel-Data-Analysis-Projects"
  Resume: "resume"
  Contact: "contact"

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# --- Exclude from processing ---
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
